APP_NAME=KmpBattery
APP_PACKAGE_NAME=com.sam.kmp_battery
APP_PACKAGE_VERSION=1.0.0
APP_DESCRIPTION=Check device battery
APP_VENDOR=Tuhin Bhowmick
APP_COPYRIGHT=Copyright 2026 Tuhin Bhowmick
APP_INSTALLER_BACKGROUND=#C4F18C
# native targets windows
WINDOWS_UPGRADE_UUID=81e0e950-5136-4ccf-9440-7b358f6906b5
WINDOWS_APPX_PUBLISHER=CN=Tuhin Bhowmick